apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment
  template:
    metadata:
      labels:
        app: Payment
    spec:
      containers:
      - name: payment
        image: returnorderimages.azurecr.io/paymentrepository:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: paymentsn

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Payment
